### ISSUE TITLE
GSoC Discussion Thread

### ISSUE THREAD

**Issue by amtrivedi91** [osu-cass/whats-fresh-api#55]
I am planning to apply for the What's Fresh GSoC task and was drafting out my proposal but am clueless about how we could "allow users to easily adapt them to other communities". What communities are we talking about here?

**Comment by Kennric** [comment]
'Other communities' might be regions with a lot of farmer's markets, where the same app could be used to find vendors of local produce. The original app was written to serve the Oregon Sea Grant, which is quite focused on the Oregon coast, obviously, but the same functionality would appeal to any community (maybe towns, states, other organizations like Sea Grant) that wants to help people find and learn about local products. This is why we chose generic names like 'Product', rather than 'Seafood', and have tried to keep the api as general as possible.

**Comment by iCHAIT** [comment]
Thanks for replying!
One last query - I understood the point of  `map-based location data entry` but could you please explain what do you mean when you are saying that the data entry processor should be simpler?
In what terms are we talking and what are you guys actually looking for?

**Comment by amtrivedi91** [comment]
Thanks for replying!
One last query - I understood the point of `map based location entry` but could you please explain how the data entry process can be made simpler?
In what terms are we talking here and what are you guys actually looking for?

**Comment by Kennric** [comment]
I will try to explain in more detail in the relevant issue, so that other's can easily find the information.

**Comment by iankronquist** [comment]
This looks like it was resolved.
